<x-app-layout><x-slot:title>HC Case Center</x-slot:title><x-page-header title="HC Process & Case Center" subtitle="Onboarding, offboarding, disciplinary, grievance, industrial relation, dokumen, klaim, dan proses operasional HC."/>
<div class="row g-3"><div class="col-xl-4"><x-card title="Buka Proses/Kasus"><form method="post" action="{{ route('enterprise.cases.store') }}" class="row g-2">@csrf
@include('enterprise._company-employee')
<x-form-select name="case_type" label="Jenis" :options="['onboarding'=>'Onboarding','offboarding'=>'Offboarding','disciplinary'=>'Disciplinary/SP','grievance'=>'Grievance','industrial_relation'=>'Hubungan Industrial','medical'=>'Medical','document'=>'Dokumen/Surat','claim'=>'Klaim','loan'=>'Pinjaman','general'=>'Lainnya']" class="col-md-6" required/>
<x-form-select name="priority" label="Prioritas" :options="['low'=>'Rendah','normal'=>'Normal','high'=>'Tinggi','critical'=>'Kritis']" value="normal" class="col-md-6" required/>
<x-form-input name="subject" label="Subjek" class="col-12" required/><x-form-input name="opened_date" label="Tanggal Dibuka" type="date" :value="today()->toDateString()" class="col-md-6" required/><x-form-input name="target_date" label="Target Selesai" type="date" class="col-md-6"/>
<x-form-select name="owner_id" label="PIC" :options="$users->pluck('name','id')" class="col-md-6"/><x-form-input name="amount" label="Nilai (bila ada)" type="number" class="col-md-6"/>
<div class="col-12"><label class="form-label">Uraian</label><textarea name="description" class="form-control form-control-sm" rows="3"></textarea></div><div class="col-12 text-end"><button class="btn btn-primary btn-sm">Buka Kasus</button></div></form></x-card></div>
<div class="col-xl-8"><x-card><form class="row g-2 mb-3"><div class="col-md-4"><select name="case_type" class="form-select form-select-sm"><option value="">Semua jenis</option>@foreach(['onboarding','offboarding','disciplinary','grievance','industrial_relation','medical','document','claim','loan','general'] as $type)<option @selected(request('case_type')===$type)>{{ $type }}</option>@endforeach</select></div><div class="col-md-3"><select name="status" class="form-select form-select-sm"><option value="">Semua status</option>@foreach(['open','in_progress','closed'] as $status)<option @selected(request('status')===$status)>{{ $status }}</option>@endforeach</select></div><div class="col"><button class="btn btn-outline-primary btn-sm">Filter</button></div></form>
@forelse($cases as $case)<div class="border rounded p-3 mb-3"><div class="d-flex justify-content-between"><div><strong>{{ $case->reference_no }} · {{ $case->subject }}</strong><div class="text-secondary">{{ strtoupper(str_replace('_',' ',$case->case_type)) }} · {{ $case->company->name }} · {{ $case->employee?->full_name ?? 'Non-karyawan' }}</div></div><x-status-badge :status="$case->status"/></div><div class="mt-2 small">PIC: {{ $case->owner?->name ?? '-' }} · Target: {{ $case->target_date?->format('d M Y') ?? '-' }} · Prioritas: {{ strtoupper($case->priority) }}</div>
<ul class="mt-2 mb-2">@forelse($case->tasks as $task)<li>{{ $task->title }} — {{ $task->assignee?->name ?? 'Belum ditugaskan' }} ({{ $task->status }}) @if($task->status!=='completed')<form class="d-inline" method="post" action="{{ route('enterprise.case-tasks.complete',$task) }}">@csrf<button class="btn btn-link btn-sm p-0">Selesai</button></form>@endif</li>@empty<li class="text-secondary">Belum ada checklist.</li>@endforelse</ul>
@if($case->status!=='closed')<form method="post" action="{{ route('enterprise.cases.tasks',$case) }}" class="row g-2">@csrf<div class="col-md-5"><input name="title" class="form-control form-control-sm" placeholder="Tambah checklist" required></div><div class="col-md-3"><select name="assigned_to" class="form-select form-select-sm"><option value="">PIC</option>@foreach($users as $user)<option value="{{ $user->id }}">{{ $user->name }}</option>@endforeach</select></div><div class="col-md-2"><input name="due_date" type="date" class="form-control form-control-sm"></div><div class="col-md-2"><button class="btn btn-outline-primary btn-sm w-100">Tambah</button></div></form><form method="post" action="{{ route('enterprise.cases.close',$case) }}" class="text-end mt-2">@csrf<button class="btn btn-success btn-sm">Tutup Kasus</button></form>@endif</div>@empty<div class="empty-state">Belum ada proses atau kasus HC.</div>@endforelse{{ $cases->links() }}</x-card></div></div></x-app-layout>
