<x-app-layout><x-slot:title>HC Policy & Workflow</x-slot:title><x-page-header title="HC Policy, Calendar & Workflow" subtitle="Kebijakan operasional dan approval berbeda per entitas group company."/>
<div class="row g-3 mb-3"><div class="col-lg-5"><x-card title="Kalender Kerja"><form method="post" action="{{ route('enterprise.calendars.store') }}" class="row g-2">@csrf
<x-form-select name="company_id" label="Perusahaan" :options="$companies->pluck('name','id')" class="col-md-6" required/><x-form-input name="code" label="Kode" class="col-md-3" required/><x-form-input name="name" label="Nama" class="col-md-6" required/><x-form-input name="timezone" label="Zona Waktu" value="Asia/Jakarta" class="col-md-6" required/>
<div class="col-12"><label class="form-label">Hari Kerja</label><div>@foreach([1=>'Sen',2=>'Sel',3=>'Rab',4=>'Kam',5=>'Jum',6=>'Sab',7=>'Min'] as $n=>$day)<label class="me-2"><input type="checkbox" name="working_days[]" value="{{ $n }}" @checked($n<=5)> {{ $day }}</label>@endforeach</div></div><div class="col-12"><label><input type="checkbox" name="is_default" value="1"> Jadikan default</label></div><div class="col-12 text-end"><button class="btn btn-primary btn-sm">Simpan Kalender</button></div></form></x-card></div>
<div class="col-lg-7"><x-card title="Approval Flow"><form method="post" action="{{ route('enterprise.flows.store') }}" class="row g-2">@csrf
<x-form-select name="company_id" label="Perusahaan" :options="$companies->pluck('name','id')" placeholder="Global" class="col-md-4"/><x-form-input name="document_type" label="Jenis Dokumen" placeholder="leave / overtime / claim" class="col-md-4" required/><x-form-input name="name" label="Nama Flow" class="col-md-4" required/>
<x-form-input name="step_order" label="Urutan" type="number" value="1" class="col-md-2" required/><x-form-select name="approver_type" label="Tipe Approver" :options="['role'=>'Role','line_manager'=>'Atasan Langsung','specific_user'=>'User Tertentu']" class="col-md-4" required/><x-form-input name="approver_role" label="Role" placeholder="admin_hr" class="col-md-3"/><x-form-select name="approver_user_id" label="User" :options="\App\Models\User::where('is_active',true)->pluck('name','id')" class="col-md-3"/>
<x-form-input name="minimum_amount" label="Nilai Minimum" type="number" class="col-md-3"/><x-form-input name="maximum_amount" label="Nilai Maksimum" type="number" class="col-md-3"/><x-form-input name="sla_hours" label="SLA (jam)" type="number" class="col-md-3"/><div class="col-md-3 align-self-end text-end"><button class="btn btn-primary btn-sm">Tambah Tahap</button></div></form></x-card></div></div>
<div class="row g-3"><div class="col-lg-6"><x-card title="Kalender & Hari Libur">@forelse($calendars as $calendar)<div class="border rounded p-2 mb-2"><strong>{{ $calendar->company->name }} · {{ $calendar->name }}</strong><div class="text-secondary">{{ $calendar->timezone }} · Hari kerja: {{ implode(', ', $calendar->working_days ?? []) }}</div><form method="post" action="{{ route('enterprise.holidays.store',$calendar) }}" class="row g-2 mt-1">@csrf<div class="col-3"><input type="date" name="holiday_date" class="form-control form-control-sm" required></div><div class="col-4"><input name="name" class="form-control form-control-sm" placeholder="Nama hari libur" required></div><div class="col-3"><select name="type" class="form-select form-select-sm"><option value="public">Nasional</option><option value="company">Perusahaan</option><option value="collective_leave">Cuti bersama</option></select></div><div class="col-2"><button class="btn btn-outline-primary btn-sm">Tambah</button></div></form><div class="small mt-2">@foreach($calendar->holidays as $holiday)<span class="badge text-bg-light me-1">{{ $holiday->holiday_date->format('d M') }} {{ $holiday->name }}</span>@endforeach</div></div>@empty<div class="empty-state">Belum ada kalender.</div>@endforelse</x-card></div>
<div class="col-lg-6"><x-card title="Workflow Aktif"><x-data-table><thead><tr><th>Dokumen</th><th>Perusahaan</th><th>Tahap</th><th>Approver</th><th>SLA</th></tr></thead><tbody>@forelse($flows as $flow)<tr><td>{{ $flow->document_type }}<div class="text-secondary">{{ $flow->name }}</div></td><td>{{ $flow->company_name ?? 'Global' }}</td><td>{{ $flow->step_order }}</td><td>{{ $flow->approver_type }} {{ $flow->approver_role }}</td><td>{{ $flow->sla_hours ? $flow->sla_hours.' jam' : '-' }}</td></tr>@empty<tr><td colspan="5" class="empty-state">Belum ada flow configurable; fallback bawaan masih berlaku.</td></tr>@endforelse</tbody></x-data-table></x-card></div></div></x-app-layout>
