<?php

use App\Http\Controllers\ApprovalController;
use App\Http\Controllers\AttendanceController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\CoreAccessController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\EnterpriseHcController;
use App\Http\Controllers\TimeAdministrationController;
use App\Http\Controllers\PayrollSetupController;
use App\Http\Controllers\LeaveController;
use App\Http\Controllers\ModuleController;
use App\Http\Controllers\OvertimeController;
use App\Http\Controllers\OrganizationController;
use App\Http\Controllers\PayrollController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserManagementController;
use Illuminate\Support\Facades\Route;

Route::redirect('/', '/login');
Route::get('/health', fn () => response()->json([
    'status' => 'ok',
    'service' => 'hcis',
    'time' => now()->toIso8601String(),
]));
Route::middleware('guest')->group(function () {
    Route::get('/login', [AuthController::class, 'login'])->name('login');
    Route::post('/login', [AuthController::class, 'store']);
    Route::get('/forgot-password', [AuthController::class, 'forgot'])->name('password.request');
    Route::post('/forgot-password', [AuthController::class, 'emailReset'])->name('password.email');
    Route::get('/reset-password/{token}', [AuthController::class, 'reset'])->name('password.reset');
    Route::post('/reset-password', [AuthController::class, 'updatePassword'])->name('password.update');
});
Route::middleware('auth')->group(function () {
    Route::post('/logout', [AuthController::class, 'destroy'])->name('logout');
    Route::get('/dashboard', [DashboardController::class, 'ess'])->name('dashboard');
    Route::get('/admin/dashboard', [DashboardController::class, 'admin'])->middleware('permission:employee.view')->name('admin.dashboard');
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::put('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::get('/me', [EmployeeController::class, 'me'])->middleware('permission:employee.view')->name('employees.me');
    Route::get('/companies', [CompanyController::class, 'index'])->middleware('permission:company.view')->name('companies.index');
    Route::get('/companies/create', [CompanyController::class, 'create'])->middleware('permission:company.create')->name('companies.create');
    Route::post('/companies', [CompanyController::class, 'store'])->middleware('permission:company.create')->name('companies.store');
    Route::get('/companies/{company}/edit', [CompanyController::class, 'edit'])->middleware('permission:company.update')->name('companies.edit');
    Route::put('/companies/{company}', [CompanyController::class, 'update'])->middleware('permission:company.update')->name('companies.update');
    Route::delete('/companies/{company}', [CompanyController::class, 'destroy'])->middleware('permission:company.delete')->name('companies.destroy');
    Route::get('/organization', [OrganizationController::class, 'index'])->middleware('permission:organization.view')->name('organization.index');
    Route::get('/organization/create', [OrganizationController::class, 'create'])->middleware('permission:organization.create')->name('organization.create');
    Route::post('/organization', [OrganizationController::class, 'store'])->middleware('permission:organization.create')->name('organization.store');
    Route::get('/organization/{unit}/edit', [OrganizationController::class, 'edit'])->middleware('permission:organization.update')->name('organization.edit');
    Route::put('/organization/{unit}', [OrganizationController::class, 'update'])->middleware('permission:organization.update')->name('organization.update');
    Route::delete('/organization/{unit}', [OrganizationController::class, 'destroy'])->middleware('permission:organization.delete')->name('organization.destroy');
    Route::post('/organization-positions', [OrganizationController::class, 'storePosition'])->middleware('permission:organization.create')->name('organization.positions.store');
    Route::delete('/organization-positions/{position}', [OrganizationController::class, 'destroyPosition'])->middleware('permission:organization.delete')->name('organization.positions.destroy');
    Route::get('/employees', [EmployeeController::class, 'index'])->middleware('permission:employee.view')->name('employees.index');
    Route::get('/employees/create', [EmployeeController::class, 'create'])->middleware('permission:employee.create')->name('employees.create');
    Route::post('/employees', [EmployeeController::class, 'store'])->middleware('permission:employee.create')->name('employees.store');
    Route::get('/employees/{employee}', [EmployeeController::class, 'show'])->middleware('permission:employee.view')->name('employees.show');
    Route::get('/employees/{employee}/edit', [EmployeeController::class, 'edit'])->middleware('permission:employee.update')->name('employees.edit');
    Route::put('/employees/{employee}', [EmployeeController::class, 'update'])->middleware('permission:employee.update')->name('employees.update');
    Route::post('/employees/{employee}/core-password-reset-request', [EmployeeController::class, 'requestCorePasswordReset'])->middleware('permission:employee.update')->name('employees.core-password-reset-request');
    Route::put('/employees/{employee}/core-password', [EmployeeController::class, 'updateCorePassword'])->middleware('permission:employee.update')->name('employees.core-password-update');
    Route::post('/employees/{employee}/core-password-reset', [EmployeeController::class, 'resetCorePassword'])->middleware('permission:employee.update')->name('employees.core-password-reset');
    Route::delete('/employees/{employee}', [EmployeeController::class, 'destroy'])->middleware('permission:employee.delete')->name('employees.destroy');
    Route::get('/attendance', [AttendanceController::class, 'index'])->middleware('permission:attendance.view')->name('attendance.index');
    Route::post('/attendance/check', [AttendanceController::class, 'check'])->middleware('permission:attendance.create')->name('attendance.check');
    Route::get('/leave', [LeaveController::class, 'index'])->middleware('permission:leave.view')->name('leave.index');
    Route::get('/leave/create', [LeaveController::class, 'create'])->middleware('permission:leave.create')->name('leave.create');
    Route::post('/leave', [LeaveController::class, 'store'])->middleware('permission:leave.create')->name('leave.store');
    Route::post('/leave/{leaveRequest}/cancel', [LeaveController::class, 'cancel'])->middleware('permission:leave.update')->name('leave.cancel');
    Route::get('/leave/{leaveRequest}/attachment', [LeaveController::class, 'attachment'])->middleware('permission:leave.view')->name('leave.attachment');
    Route::get('/overtime', [OvertimeController::class, 'index'])->middleware('permission:overtime.view')->name('overtime.index');
    Route::get('/overtime/create', [OvertimeController::class, 'create'])->middleware('permission:overtime.create')->name('overtime.create');
    Route::post('/overtime', [OvertimeController::class, 'store'])->middleware('permission:overtime.create')->name('overtime.store');
    Route::get('/approvals', [ApprovalController::class, 'index'])->middleware('permission:approval.view')->name('approvals.index');
    Route::post('/approvals/{approvalRequest}', [ApprovalController::class, 'act'])->middleware('permission:approval.approve')->name('approvals.act');
    Route::get('/payroll', [PayrollController::class, 'index'])->middleware('permission:payroll.view')->name('payroll.index');
    Route::post('/payroll', [PayrollController::class, 'store'])->middleware('permission:payroll.create')->name('payroll.store');
    Route::post('/payroll/{period}/run', [PayrollController::class, 'run'])->middleware('permission:payroll.update')->name('payroll.run');
    Route::get('/payslips/{payslip}/pdf', [PayrollController::class, 'pdf'])->middleware('permission:payroll.view')->name('payslips.pdf');
    Route::get('/users', [UserManagementController::class, 'index'])->middleware('permission:user.view')->name('users.index');
    Route::get('/users/create', [UserManagementController::class, 'create'])->middleware('permission:user.create')->name('users.create');
    Route::post('/users', [UserManagementController::class, 'store'])->middleware('permission:user.create')->name('users.store');
    Route::get('/users/{user}/edit', [UserManagementController::class, 'edit'])->middleware('permission:user.update')->name('users.edit');
    Route::put('/users/{user}', [UserManagementController::class, 'update'])->middleware('permission:user.update')->name('users.update');
    Route::delete('/users/{user}', [UserManagementController::class, 'destroy'])->middleware('permission:user.delete')->name('users.destroy');
    Route::get('/roles', [RoleController::class, 'index'])->middleware('permission:role.view')->name('roles.index');
    Route::post('/roles/sync-defaults', [RoleController::class, 'syncDefaults'])->middleware('permission:role.create')->name('roles.sync-defaults');
    Route::get('/roles/create', [RoleController::class, 'create'])->middleware('permission:role.create')->name('roles.create');
    Route::post('/roles', [RoleController::class, 'store'])->middleware('permission:role.create')->name('roles.store');
    Route::get('/roles/{role}/edit', [RoleController::class, 'edit'])->middleware('permission:role.update')->name('roles.edit');
    Route::put('/roles/{role}', [RoleController::class, 'update'])->middleware('permission:role.update')->name('roles.update');
    Route::delete('/roles/{role}', [RoleController::class, 'destroy'])->middleware('permission:role.delete')->name('roles.destroy');
    Route::get('/core-access', [CoreAccessController::class, 'index'])->middleware('permission:core_access.view')->name('core-access.index');
    Route::post('/core-access/companies/{company}/modules', [CoreAccessController::class, 'updateCompanyModules'])->middleware('permission:core_access.update')->name('core-access.company-modules');
    Route::post('/core-access/roles', [CoreAccessController::class, 'storeRole'])->middleware('permission:core_access.update')->name('core-access.roles.store');
    Route::post('/core-access/employees/{employee}/roles', [CoreAccessController::class, 'updateEmployeeRoles'])->middleware('permission:core_access.update')->name('core-access.employee-roles');
    Route::get('/reports/employees.xlsx', [ReportController::class, 'employeesExcel'])->middleware('permission:report.export')->name('reports.employees.excel');
    Route::get('/reports/employees.pdf', [ReportController::class, 'employeesPdf'])->middleware('permission:report.export')->name('reports.employees.pdf');
    Route::prefix('enterprise')->name('enterprise.')->group(function () {
        Route::get('/lifecycle', [EnterpriseHcController::class, 'lifecycle'])->middleware('permission:lifecycle.view')->name('lifecycle');
        Route::post('/contracts', [EnterpriseHcController::class, 'storeContract'])->middleware('permission:lifecycle.create')->name('contracts.store');
        Route::post('/contracts/{contract}/approve', [EnterpriseHcController::class, 'approveContract'])->middleware('permission:lifecycle.approve')->name('contracts.approve');
        Route::post('/employee-actions', [EnterpriseHcController::class, 'storeAction'])->middleware('permission:lifecycle.create')->name('actions.store');
        Route::post('/employee-actions/{action}/approve', [EnterpriseHcController::class, 'approveAction'])->middleware('permission:lifecycle.approve')->name('actions.approve');
        Route::get('/cases', [EnterpriseHcController::class, 'cases'])->middleware('permission:hc_case.view')->name('cases');
        Route::post('/cases', [EnterpriseHcController::class, 'storeCase'])->middleware('permission:hc_case.create')->name('cases.store');
        Route::post('/cases/{case}/tasks', [EnterpriseHcController::class, 'addCaseTask'])->middleware('permission:hc_case.update')->name('cases.tasks');
        Route::post('/case-tasks/{task}/complete', [EnterpriseHcController::class, 'completeCaseTask'])->middleware('permission:hc_case.update')->name('case-tasks.complete');
        Route::post('/cases/{case}/close', [EnterpriseHcController::class, 'closeCase'])->middleware('permission:hc_case.update')->name('cases.close');
        Route::get('/policies', [EnterpriseHcController::class, 'policies'])->middleware('permission:policy.view')->name('policies');
        Route::post('/calendars', [EnterpriseHcController::class, 'storeCalendar'])->middleware('permission:policy.create')->name('calendars.store');
        Route::post('/calendars/{calendar}/holidays', [EnterpriseHcController::class, 'storeHoliday'])->middleware('permission:policy.create')->name('holidays.store');
        Route::post('/approval-flows', [EnterpriseHcController::class, 'storeFlow'])->middleware('permission:policy.create')->name('flows.store');
        Route::get('/assets', [EnterpriseHcController::class, 'assets'])->middleware('permission:asset.view')->name('assets');
        Route::post('/assets', [EnterpriseHcController::class, 'storeAsset'])->middleware('permission:asset.create')->name('assets.store');
        Route::post('/assets/{asset}/assign', [EnterpriseHcController::class, 'assignAsset'])->middleware('permission:asset.update')->name('assets.assign');
        Route::post('/asset-assignments/{assignment}/return', [EnterpriseHcController::class, 'returnAsset'])->middleware('permission:asset.update')->name('assets.return');
        Route::get('/talent', [EnterpriseHcController::class, 'talent'])->middleware('permission:performance.view|learning.view|career.view')->name('talent');
        Route::post('/performance-cycles', [EnterpriseHcController::class, 'storeCycle'])->middleware('permission:performance.create')->name('cycles.store');
        Route::post('/performance-cycles/{cycle}/launch', [EnterpriseHcController::class, 'launchCycle'])->middleware('permission:performance.update')->name('cycles.launch');
        Route::post('/learning-programs', [EnterpriseHcController::class, 'storeLearning'])->middleware('permission:learning.create')->name('learning.store');
        Route::post('/learning-programs/{program}/participants', [EnterpriseHcController::class, 'addParticipant'])->middleware('permission:learning.update')->name('learning.participants');
        Route::post('/succession-plans', [EnterpriseHcController::class, 'storeSuccession'])->middleware('permission:career.create')->name('succession.store');
        Route::get('/reports', [EnterpriseHcController::class, 'reports'])->middleware('permission:report.view')->name('reports');
        Route::get('/time-administration', [TimeAdministrationController::class, 'index'])->middleware('permission:shift.view|attendance.view|leave.view|overtime.view')->name('time');
        Route::post('/shifts', [TimeAdministrationController::class, 'storeShift'])->middleware('permission:shift.create')->name('shifts.store');
        Route::post('/schedules', [TimeAdministrationController::class, 'storeSchedule'])->middleware('permission:shift.create')->name('schedules.store');
        Route::post('/attendance-corrections', [TimeAdministrationController::class, 'storeCorrection'])->middleware('permission:attendance.update')->name('corrections.store');
        Route::post('/attendance-corrections/{correction}/approve', [TimeAdministrationController::class, 'approveCorrection'])->middleware('permission:attendance.approve')->name('corrections.approve');
        Route::post('/leave-types', [TimeAdministrationController::class, 'storeLeaveType'])->middleware('permission:leave.create')->name('leave-types.store');
        Route::post('/overtime-policies', [TimeAdministrationController::class, 'storeOvertimePolicy'])->middleware('permission:overtime.create')->name('overtime-policies.store');
        Route::get('/payroll-control', [PayrollSetupController::class, 'index'])->middleware('permission:payroll.view|tax.view|bpjs.view')->name('payroll-setup');
        Route::post('/statutory-configs', [PayrollSetupController::class, 'storeConfig'])->middleware('permission:payroll.create|tax.create|bpjs.create')->name('statutory.store');
        Route::post('/statutory-profiles', [PayrollSetupController::class, 'storeProfile'])->middleware('permission:payroll.update|tax.update|bpjs.update')->name('statutory-profiles.store');
        Route::post('/payroll-adjustments', [PayrollSetupController::class, 'storeAdjustment'])->middleware('permission:payroll.create')->name('adjustments.store');
    });
    Route::get('/modules/{module}', [ModuleController::class, 'index'])->name('modules.index');
    Route::post('/modules/{module}', [ModuleController::class, 'store'])->name('modules.store');
    Route::delete('/modules/{module}/{record}', [ModuleController::class, 'destroy'])->name('modules.destroy');
});
